version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    commit-message:
      prefix: chore
      include: scope
    groups:
      kotlin:
        patterns:
          - "jvm"
          - "plugin.spring"
          - "plugin.serialization"
      exposed:
        patterns:
          - "org.jetbrains.exposed:exposed-spring-boot-starter"
          - "org.jetbrains.exposed:exposed-kotlin-datetime"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    commit-message:
      prefix: chore
      include: scope
