services:
  database:
    image: postgres:17.0
    environment:
      POSTGRES_USER: "test-user"
      POSTGRES_PASSWORD: "test-password"
      POSTGRES_DB: "test"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  data-test:
