spring.main.banner-mode=off
#
app.datasource.ro.jdbc-url=jdbc:postgresql://database:5432/tv-tracker
app.datasource.ro.username=test-user
app.datasource.ro.password=test-password
#
app.datasource.rw.jdbc-url=jdbc:postgresql://database:5432/tv-tracker
app.datasource.rw.username=test-user
app.datasource.rw.password=test-password
#
logging.level.Exposed=error
#
springdoc.api-docs.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.enable-groovy=false
springdoc.enable-hateoas=false
springdoc.enable-kotlin=false
springdoc.enable-spring-security=false
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/openapi.yaml
springdoc.swagger-ui.path=docs
#
server.error.include-message=always
